common:
    lid_topic:  "/livox/lidar"

preprocess:
    lidar_type: 1                # Livox series LiDAR
    feature_extract_en: false
    scan_line: 6
    blind: 1
    point_filter_num: 3

initialization:
    cut_frame: true
    cut_frame_num: 5           # 分帧数
    cut_frame_init_num: 5       # 如果分帧的话 
    orig_odom_freq: 10
    mean_acc_norm: 9.805
    online_refine_time: 20
    data_accum_length: 500
    Rot_LI_cov: [ 0.00005, 0.00005, 0.00005 ]
    Trans_LI_cov: [ 0.0001, 0.0001, 0.0001 ]

mapping:
    filter_size_surf: 0.3
    filter_size_map: 0.3
    gyr_cov: 0.0001             # lgo角速度噪声协方差
    acc_cov: 1             # lgo线速度噪声协方差
    # gyr_cov: 1.01             # lo角速度噪声协方差
    # acc_cov: 1.01             # lo线速度噪声协方差
    # gyr_cov: 0.1             # lio角速度噪声协方差
    # acc_cov: 0.1             # lio线速度噪声协方差
    det_range: 100.0
    cov_lidar: 0.001            # 雷达观测噪声协方差
    max_iteration: 20           # iekf最大迭代次数
    max_undistort: 5            # 最大去畸变次数  与 最大迭代次数 二者达到一个即退出迭代
    cube_side_length: 2000
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    extrinsic_T: [ 0.05512, 0.02226, -0.0297 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
