common:
    lid_topic:  "/rslidar_points"
    imu_topic:  "/mavros/imu/data_raw"
preprocess:
    lidar_type: 6                # Robosense LiDAR
    scan_line: 128
    blind: 2
    feature_extract_en: false
    point_filter_num: 2

initialization:
    cut_frame_num: 3 # must be positive integer
    orig_odom_freq: 10
    cut_frame_init_num: 20       # 如果分帧的话 从第几帧开始分帧 默认固态 5 机械 20
    orig_odom_freq: 10
    mean_acc_norm: 9.805
    online_refine_time: 15
    data_accum_length: 500
    Rot_LI_cov: [ 0.00005, 0.00005, 0.00005 ]
    Trans_LI_cov: [ 0.0001, 0.0001, 0.0001 ]
    extrinsic_T: [ 0.05512, 0.02226, -0.0297 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
mapping:
    filter_size_surf: 0.05
    filter_size_map: 0.15
    gyr_cov: 0.5
    acc_cov: 0.5
    det_range: 100.0
    cov_lidar: 0.001
    max_iteration: 20
    max_undistort: 3
    cube_side_length: 2000
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
